AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Fargate cluster running containers in a public subnet. Only supports
             public facing load balancer, and public service discovery namespaces.

Resources:  
  Cluster:
    Type: 'AWS::ECS::Cluster'
    Properties: 
       CapacityProviders:
          - FARGATE
       ClusterName: ECS-CLUSTER
  

# These output values will be available to service templates to use.
# Outputs:
  # ClusterName:
    # Description: The name of the ECS cluster
    # Value: !Ref 'ECSCluster'
  # ECSTaskExecutionRole:
    # Description: The ARN of the ECS role
    # Value: !GetAtt 'ECSTaskExecutionRole.Arn'
  # ContainerSecurityGroup:
    # Description: A security group used to allow Fargate containers to receive traffic
    # Value: !Ref 'ContainerSecurityGroup'
