schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "FargateEnvironmentInput"
  types:
    FargateEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_cidr:
          type: string
          description: "The CIDR range for your VPC"
          default: 192.168.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_one_cidr:
          type: string
          description: "The CIDR range for private subnet one"
          default: 192.168.0.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_two_cidr:
          type: string
          description: "The CIDR range for private subnet two"
          default: 192.168.1.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
